## Estadistica Aplicada

## Sesion 3-15 Agosto

## Bryan Alejandro Estrada Rodriguez

## Grupo 42

## Tuplas
Es una coleccion de objetos inmutables (no se puede cambiar)

In [1]:
tupla_alumno = ('Jaun', 'Perez', 17)

In [2]:
type(tupla_alumno)

tuple

In [3]:
tupla_alumno.remove('Juan')

AttributeError: 'tuple' object has no attribute 'remove'

## Diccionario (mapeo de valores)
clave(variable) - Valor

In [4]:
dic1_alumno = {'Nombre':'Juan', 'Apellido':'Perez'}

In [5]:
type(dic1_alumno)

dict

In [6]:
dic_grupo = {'Nombre':['Jime','Raul','Ana'],'Edad':[17,21,15]}

In [7]:
dic_grupo['Nombre']

['Jime', 'Raul', 'Ana']

In [8]:
dic_grupo.keys()

dict_keys(['Nombre', 'Edad'])

In [9]:
dic_grupo.values()

dict_values([['Jime', 'Raul', 'Ana'], [17, 21, 15]])

## Pandas
Datos estructurados. Pandas esta construida sobre NUMPY, todo lo de numpy aplica en pandas.
Pandas tiene 3 estructuras basicas:
1. Series (Unidimensionales)
2. Dataframes (Filas y columnas)
3. Panel (Tiempo)

In [10]:
import pandas as pd

Suponemos que conocemos la edad de las siguientes personas: Perdo 12, Juan 17, Jime 21, Rosa 22

In [11]:
edades = [12,17,21,22]

In [12]:
edades

[12, 17, 21, 22]

In [15]:
serie_edades = pd.Series(edades,index=['Pedro','Juan','Jime','Rosa'])

In [16]:
type(serie_edades)

pandas.core.series.Series

In [18]:
serie_edades.mean()

18.0

In [19]:
serie_edades.median()

19.0

## Dataframe
Datos en filas y columnas

In [26]:
alumno_1 =['Juan','Perez',23 ]
alumno_2 =['Raul','Gonzalez',17]
alumno_3 =['Jimena','Rosas',20]
alumno_4 =['Alejandra','Saldaña',21]

In [27]:
grupo_estadistica = [alumno_1,alumno_2,alumno_3,alumno_4]

In [28]:
grupo_estadistica

[['Juan', 'Perez', 23],
 ['Raul', 'Gonzalez', 17],
 ['Jimena', 'Rosas', 20],
 ['Alejandra', 'Saldaña', 21]]

In [30]:
df_clase=pd.DataFrame(grupo_estadistica,columns=['Nombre','Apellido','Edad'])

In [32]:
type(df_clase)

pandas.core.frame.DataFrame

In [33]:
df_clase

      Nombre  Apellido  Edad
0       Juan     Perez    23
1       Raul  Gonzalez    17
2     Jimena     Rosas    20
3  Alejandra   Saldaña    21

Nombre, Apellido, Edad = Columns
0,1,2,3 = Index

In [35]:
df_clase.columns

Index(['Nombre', 'Apellido', 'Edad'], dtype='object')

In [36]:
df_clase.index

RangeIndex(start=0, stop=4, step=1)

    Start = Empieza en 0 //
    stpo = Hay 4 objetos 
    Step = Va de 1 en 1

In [37]:
df_clase['Municipio'] =['Mty','Escobedo','Apodaca','Santiago']

In [38]:
df_clase

      Nombre  Apellido  Edad Municipio
0       Juan     Perez    23       Mty
1       Raul  Gonzalez    17  Escobedo
2     Jimena     Rosas    20   Apodaca
3  Alejandra   Saldaña    21  Santiago

In [39]:
df_clase['Edad en Dias'] = df_clase['Edad']*365

In [40]:
df_clase

      Nombre  Apellido  Edad Municipio  Edad en Dias
0       Juan     Perez    23       Mty          8395
1       Raul  Gonzalez    17  Escobedo          6205
2     Jimena     Rosas    20   Apodaca          7300
3  Alejandra   Saldaña    21  Santiago          7665

## Seleccionar elementos de un DATAFRAME
1. Selecc Estandar
2. Seleccion por .iloc
3. Seleccion por .loc
4. Seleccion condicional

In [41]:
## Selecc estandar
df_clase['Edad']

0    23
1    17
2    20
3    21
Name: Edad, dtype: int64

In [42]:
## 
df_clase[['Edad','Nombre']]

   Edad     Nombre
0    23       Juan
1    17       Raul
2    20     Jimena
3    21  Alejandra

In [48]:
## Selecc Estandar se puede seleccionar una sola columna mientras pongas el numero de columna que quieres : y el siguiente numero
df_clase[1:2]

  Nombre  Apellido  Edad Municipio  Edad en Dias
1   Raul  Gonzalez    17  Escobedo          6205

In [49]:
df_clase[0:2]['Edad']

0    23
1    17
Name: Edad, dtype: int64

## Seleccion .iloc (Posicion)
dataframe.iloc[filas,columnas]

In [52]:
#
df_clase.iloc[0,2]

23

In [57]:
df_clase.iloc[0:2,2]

0    23
1    17
Name: Edad, dtype: int64

In [59]:
df_clase.iloc[:,[1,2]]

   Apellido  Edad
0     Perez    23
1  Gonzalez    17
2     Rosas    20
3   Saldaña    21

In [60]:
df_clase

      Nombre  Apellido  Edad Municipio  Edad en Dias
0       Juan     Perez    23       Mty          8395
1       Raul  Gonzalez    17  Escobedo          6205
2     Jimena     Rosas    20   Apodaca          7300
3  Alejandra   Saldaña    21  Santiago          7665

In [62]:
df_clase = df_clase.set_index('Nombre')

In [63]:
df_clase

           Apellido  Edad Municipio  Edad en Dias
Nombre
Juan          Perez    23       Mty          8395
Raul       Gonzalez    17  Escobedo          6205
Jimena        Rosas    20   Apodaca          7300
Alejandra   Saldaña    21  Santiago          7665

In [64]:
df_clase.columns

Index(['Apellido', 'Edad', 'Municipio', 'Edad en Dias'], dtype='object')

In [66]:
df_clase.index

Index(['Juan', 'Raul', 'Jimena', 'Alejandra'], dtype='object', name='Nombre')

## Seleccion por .loc (Etiquetas) Nombres
dataframe.loc[nombre de filas , nombre 'Edad']

In [68]:
df_clase.loc[:,'Edad']

Nombre
Juan         23
Raul         17
Jimena       20
Alejandra    21
Name: Edad, dtype: int64

In [69]:
df_clase.loc['Juan','Edad']

23

In [72]:
## Seleccion por SQL
df_clase.Edad

Nombre
Juan         23
Raul         17
Jimena       20
Alejandra    21
Name: Edad, dtype: int64

In [74]:
df_clase

           Apellido  Edad Municipio  Edad en Dias
Nombre
Juan          Perez    23       Mty          8395
Raul       Gonzalez    17  Escobedo          6205
Jimena        Rosas    20   Apodaca          7300
Alejandra   Saldaña    21  Santiago          7665

In [75]:
df_clase[df_clase['Edad']>=18]

          Apellido  Edad Municipio  Edad en Dias
Nombre
Juan         Perez    23       Mty          8395
Jimena       Rosas    20   Apodaca          7300
Alejandra  Saldaña    21  Santiago          7665

In [76]:
df_clase[df_clase['Municipio']=='Apodaca']

       Apellido  Edad Municipio  Edad en Dias
Nombre
Jimena    Rosas    20   Apodaca          7300

In [77]:
# Ordenamiento
df_clase.sort_values('Edad')

           Apellido  Edad Municipio  Edad en Dias
Nombre
Raul       Gonzalez    17  Escobedo          6205
Jimena        Rosas    20   Apodaca          7300
Alejandra   Saldaña    21  Santiago          7665
Juan          Perez    23       Mty          8395

In [78]:
df_clase.sort_values('Nombre')

           Apellido  Edad Municipio  Edad en Dias
Nombre
Alejandra   Saldaña    21  Santiago          7665
Jimena        Rosas    20   Apodaca          7300
Juan          Perez    23       Mty          8395
Raul       Gonzalez    17  Escobedo          6205

In [80]:
## ordenar de mayor a menor 
df_clase.sort_values('Edad',ascending=False)

           Apellido  Edad Municipio  Edad en Dias
Nombre
Juan          Perez    23       Mty          8395
Alejandra   Saldaña    21  Santiago          7665
Jimena        Rosas    20   Apodaca          7300
Raul       Gonzalez    17  Escobedo          6205

In [81]:
df_clase.sort_values(['Edad','Apellido'])

           Apellido  Edad Municipio  Edad en Dias
Nombre
Raul       Gonzalez    17  Escobedo          6205
Jimena        Rosas    20   Apodaca          7300
Alejandra   Saldaña    21  Santiago          7665
Juan          Perez    23       Mty          8395

In [83]:
# numpy 
df_clase['Edad'].mean()

20.25

In [84]:
df_clase['Edad'].std(ddof=1)

2.5

In [91]:
# suma
df_clase['Edad'].sum()

81

In [92]:
import numpy as np

In [93]:
# np.where (condicion, valor si condicion, valor si condicion no se cumple )
df_clase['Mayoria de Edad'] = np.where(df_clase['Edad']>=18, 'Mayor','Menor')

In [94]:
df_clase

           Apellido  Edad Municipio  Edad en Dias Mayoria de Edad
Nombre
Juan          Perez    23       Mty          8395           Mayor
Raul       Gonzalez    17  Escobedo          6205           Menor
Jimena        Rosas    20   Apodaca          7300           Mayor
Alejandra   Saldaña    21  Santiago          7665           Mayor

## np.select
np.select(condicion, valor condicion, valor si ninguna condicion se cumple)

In [96]:
condiciones = [df_clase['Edad']<=17,
              df_clase['Edad']<=23,
              df_clase['Edad']>=23]
valores = ['Preparatoria','Universidad','Trabajando']
df_clase['Situacion']= np.select(condiciones,valores,default='Invalido')

In [97]:
df_clase

,Apellido,Edad,Municipio,Edad en Dias,Mayoria de Edad,Situacion
Nombre,,,,,,
Juan,Perez,23,Mty,8395,Mayor,Universidad
Raul,Gonzalez,17,Escobedo,6205,Menor,Preparatoria
Jimena,Rosas,20,Apodaca,7300,Mayor,Universidad
Alejandra,Saldaña,21,Santiago,7665,Mayor,Universidad

In [98]:
df_clase.count()

Apellido           4
Edad               4
Municipio          4
Edad en Dias       4
Mayoria de Edad    4
Situacion          4
dtype: int64

In [99]:
df_clase['Edad'].count()

4

In [100]:
df_clase.value_counts('Mayoria de Edad')

Mayoria de Edad
Mayor    3
Menor    1
dtype: int64

In [105]:
df_clase.groupby('Mayoria de Edad').mean(numeric_only=True).round(1)['Edad']

Mayoria de Edad
Mayor    21.3
Menor    17.0
Name: Edad, dtype: float64

In [107]:
# aggregate agg
df_clase.agg('count')

Apellido           4
Edad               4
Municipio          4
Edad en Dias       4
Mayoria de Edad    4
Situacion          4
dtype: int64

In [116]:
df_clase.groupby('Mayoria de Edad')['Edad'].agg(['mean','std']).round(1)

                 mean  std
Mayoria de Edad
Mayor            21.3  1.5
Menor            17.0  NaN

In [117]:
calificaciones = pd.read_csv('https://raw.githubusercontent.com/jimmyzac/Estadistica-Aplicada-FCFM-UANL/main/bases_datos/Calificaciones.csv')

In [122]:
calificaciones.head()

   Id   Nombre   Apellido  Calficación Final
0   1  ANTONIO     GARCIA                 73
1   2   MANUEL  FERNANDEZ                 19
2   3     JOSE   GONZALEZ                 38
3   4    DAVID      PEREZ                 14
4   5     JUAN      LOPEZ                 99

Para ver las primeras 5 Filas

In [123]:
calificaciones.tail()

    Id       Nombre   Apellido  Calficación Final
23  24         LUIS  DOMINGUEZ                 12
24  25      ALBERTO      ORTIZ                 99
25  26  JUAN CARLOS     IBAÑEZ                 43
26  27       ALVARO    RAMIREZ                 40
27  28       ADRIAN       SAEZ                  7

In [124]:
calificaciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 28 non-null     int64
 1   Nombre             28 non-null     object
 2   Apellido           28 non-null     object
 3   Calficación Final  28 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.0+ KB

In [125]:
calificaciones.shape

(28, 4)

In [126]:
# Estadisticas descriptivas
calificaciones.describe()

              Id  Calficación Final
count  28.000000          28.000000
mean   14.500000          52.000000
std     8.225975          34.113102
min     1.000000           1.000000
25%     7.750000          18.500000
50%    14.500000          48.500000
75%    21.250000          85.250000
max    28.000000         100.000000

In [130]:
calificaciones=calificaciones.rename(columns={'Calficación Final':'Calificación Final'})

In [131]:
calificaciones.head()

   Id   Nombre   Apellido  Calificación Final
0   1  ANTONIO     GARCIA                  73
1   2   MANUEL  FERNANDEZ                  19
2   3     JOSE   GONZALEZ                  38
3   4    DAVID      PEREZ                  14
4   5     JUAN      LOPEZ                  99

In [137]:
calificaciones=calificaciones.loc[:,calificaciones.columns!='Id']

In [138]:
calificaciones

              Nombre   Apellido  Calificación Final
0            ANTONIO     GARCIA                  73
1             MANUEL  FERNANDEZ                  19
2               JOSE   GONZALEZ                  38
3              DAVID      PEREZ                  14
4               JUAN      LOPEZ                  99
5       JOSE ANTONIO  RODRIGUEZ                  66
6             JAVIER    SANCHEZ                  46
7          JOSE LUIS      GOMEZ                  89
8   FRANCISCO JAVIER    JIMENEZ                  10
9             CARLOS       RUIZ                  62
10             JESUS     ALONSO                  94
11         ALEJANDRO  HERNANDEZ                  17
12            MIGUEL       DIAZ                  85
13       JOSE MANUEL  GUTIERREZ                  34
14            RAFAEL    ALVAREZ                  86
15      MIGUEL ANGEL     MORENO                 100
16             PEDRO      MUÑOZ                   1
17             PABLO     BLANCO                  64
18             ANGEL        GIL                 100
19            SERGIO    AGUIRRE                   2
20        JOSE MARIA       DIEZ                  29
21          FERNANDO    SALAZAR                  51
22             JORGE      RAMOS                  76
23              LUIS  DOMINGUEZ                  12
24           ALBERTO      ORTIZ                  99
25       JUAN CARLOS     IBAÑEZ                  43
26            ALVARO    RAMIREZ                  40
27            ADRIAN       SAEZ                   7

In [141]:
calificaciones['Situacion'] = np.where(calificaciones['Calificación Final']>=70, 'Aprobado','Reprobado')

In [148]:
calificaciones.head()

    Nombre   Apellido  Calificación Final  Situacion
0  ANTONIO     GARCIA                  73   Aprobado
1   MANUEL  FERNANDEZ                  19  Reprobado
2     JOSE   GONZALEZ                  38  Reprobado
3    DAVID      PEREZ                  14  Reprobado
4     JUAN      LOPEZ                  99   Aprobado

In [145]:
calificaciones.value_counts('Situacion')

Situacion
Reprobado    18
Aprobado     10
dtype: int64

In [147]:
calificaciones.groupby('Situacion').mean(numeric_only=True).round(1)

           Calificación Final
Situacion
Aprobado                 90.1
Reprobado                30.8